# Theme
# https://github.com/alacritty/alacritty-theme
import = [
  "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[window]
startup_mode = "Maximized"
[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 14.0
[cursor]
style = { shape = "Beam", blinking = "On" }
