# Theme
# https://github.com/alacritty/alacritty-theme
# import = ["~/.config/alacritty/themes/themes/solarized_dark.toml"]
import = ["~/.config/alacritty/themes/themes/solarized_light.toml"]

[window]
startup_mode = "Maximized"
padding = { x = 4, y = 0 }
[font]
normal = { family = "Iosevka", style = "Regular" }
size = 14.0
[cursor]
style = { shape = "Beam", blinking = "On" }
