# Theme
# https://github.com/alacritty/alacritty-theme
# Dark theme
import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
# Light theme
# import = ["~/.config/alacritty/themes/themes/alabaster.toml"]

[window]
startup_mode = "Maximized"
padding = { x = 4, y = 0 }
[font]
normal = { family = "Iosevka Term", style = "Light" }
bold = { family = "Iosevka Term", style = "Bold" }
italic = { family = "Iosevka Term", style = "Light Italic" }
bold_italic = { family = "Iosevka Term", style = "Bold Italic" }
size = 14.0
