# Theme
# https://github.com/alacritty/alacritty-theme
# Dark theme
import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
# Light theme
# import = ["~/.config/alacritty/themes/themes/alabaster.toml"]

[window]
startup_mode = "Maximized"
padding = { x = 4, y = 0 }
[font]
normal = { family = "Iosevka Term", style = "Light" }
size = 14.0
