# Theme
# https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/gruvbox_light.toml"]

[window]
startup_mode = "Maximized"
[font]
normal = { family = "Iosevka", style = "Regular" }
size = 14.0
[cursor]
style = { shape = "Beam", blinking = "On" }
